const itemsData = [
  {
    id: 1,
    link: '#',
    category: 'product',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 2,
    link: '#',
    category: 'product',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'product',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'product',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'product',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'product',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'product',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'product',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'design',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'design',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'design',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'design',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'design',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'design',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'design',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'design',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'ETC',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'ETC',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'ETC',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'ETC',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'ETC',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'ETC',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'ETC',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
  {
    id: 0,
    link: '#',
    category: 'ETC',
    name: '',
    score: '4.5',
    review: '',
    price: '',
    createdAt: '',
    image: '',
    tags: [],
  },
];

export default itemsData;